### ISSUE TITLE
Size of the footprint for the 100 uF cap is small

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#13]
The 100 uF cap we have is of size 2917 whereas the footprint on both the piezo and MEMS board seems more like 1206.

**Comment by nkakarla1** [comment]
Footprint changed to 7343, which is the same as 2917. The difference in numbering is due to change in metrics (inches to mm)

**Comment by Preetisar** [comment]
Reopening this for now, until size is confirmed by Ali.

**Comment by nkakarla1** [comment]
Changed to 7343 on MEMS board too
