### ISSUE TITLE
DPDT switch connected wrongly in the piezo board

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#18]
Currently pin 3 of the DPDT switch is connected to the TRS connector and pin 6 is connected to nothing. Instead the TRS connector should be connected to pin 6 of the DPDT switch and pin 3 should not be connected to anything.

**Comment by nkakarla1** [comment]
connections for pin 3 and 6 updated: pin 3 not connected to anything and TRS connector connected to pin 6
