### ISSUE TITLE
Change resistor values of R20 and R21 in voltage regulation step-down

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#21]
Change the value of the resistor R20 to 100K and the value of resistor R21 to 11K.

**Comment by nkakarla1** [comment]
resistor values uodated in Piezo board.

**Comment by Preetisar** [comment]
The resistor values have to be updated on the MEMS board too. This issue has labels for both.

**Comment by nkakarla1** [comment]
The values of resistors changed on MEMS board too
