### ISSUE TITLE
Switches are not labeled well on the Piezo and MEMS board

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#22]
The switches are not clearly labeled on both the piezo and the MEMS board. The switch labels should also include what the switch does, and which position of the switch is for what purpose. It should be a word like 'on' and 'off', 'mixer' and 'headphone' or 'mic'.

**Comment by nkakarla1** [comment]
Please provide the labels for specific switches.

**Comment by nkakarla1** [comment]
On/Off added to MEMS board
