### ISSUE TITLE
potentiometer device has wrong symbol, device name, package name

### ISSUE THREAD

**Issue by batchku** [cmuartfab/eagle#23]
the device used for the 50k pot in `piezo-preamp-tickler_V3-6_single-supply-OPA1642.sch` has multiple issues.  It looks like @nkakarla1 made a whole new device; this is incorrect.

![image](https://user-images.githubusercontent.com/518356/36131827-b952c926-1028-11e8-9411-61a4c3737114.png)

instead, you should just modify the existing device to have the new changes; 

the correct device is called `POT` and it's in the `cmuartfab` library:

![image](https://user-images.githubusercontent.com/518356/36131816-acc5ec74-1028-11e8-8e7a-1a77d8f85f6d.png)

the variant package name should follow the conventions in that device; it should be called `POT-` followed by the manufacturer part number.

**Comment by nkakarla1** [comment]
Got the part number from @Preetisar  for 50K pot in  piezo-preamp-tickler_V3-6_single-supply-OPA1642.sch to be RV100F-30-4K1-B50K. Since the package for this component is already available in the cmuartfab library, the faulty new device is replaced by THUMBPOT14MM package.
