### ISSUE TITLE
Piezo preamp silk screen is a MESS

### ISSUE THREAD

**Issue by batchku** [cmuartfab/eagle#26]
Inconsistent sizes, fonts, poorly placed labels, some overlap, some run off the board.

![image](https://user-images.githubusercontent.com/518356/36947800-df179fbc-1f9e-11e8-8114-50eaf6659159.png)

All component silk screens should be like that of R16:

![image](https://user-images.githubusercontent.com/518356/36947802-f69f2574-1f9e-11e8-8d2d-2a212bf6afce.png)

**Comment by nkakarla1** [comment]
Board updated to have consistent fonts and labels
