### ISSUE TITLE
Change L2 Inductor Package to 1008

### ISSUE THREAD

**Issue by batchku** [cmuartfab/eagle#27]
Need larger current inductor:

https://www.digikey.com/product-detail/en/abracon-llc/AISC-1008F-2R7J-T/535-10570-1-ND/2335527

![image](https://user-images.githubusercontent.com/518356/36948104-91721db4-1fa3-11e8-999e-5137e359a6d6.png)

![image](https://user-images.githubusercontent.com/518356/36948110-9bca3314-1fa3-11e8-9bb5-32aa1654ac1a.png)

**Comment by Preetisar** [comment]
I am not sure if this is the right size and package. I think we should simply switch back to the size on the previous version of the piezo board which is CR54.
