### ISSUE TITLE
Pins of the POT in the MEMS board are wired incorrectly.

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#29]
Correct wiring of the pins is described below, with the pin number 1 to 6 counted from the back of the board, since the POT will be soldered on the back.
Pin 1 of the pot connects to pin 1 of the opamp.
Pin 2 of the pot connects to pin 2 of the opamp.
Pin 3 of the pot connects to pin 6 of the opamp.
Pin 4 of the pot connects to pin 7 of the opamp.
Pin 5 and and Pin 6 of the POT are not connected to anything.

**Comment by nkakarla1** [comment]
Connecting this way would just put a constant 20k resistance between the two terminals. Please confirm if this is the requirement. If so, the pot can be replaced by resistor to save space,
