### ISSUE TITLE
poor placement of parts

### ISSUE THREAD

**Issue by batchku** [cmuartfab/eagle#36]
Component placement in both boards needs significant modification.  The problem is that components that are connected to another another in the schematic are placed far away (and in seemlingly random places) in the board; this causes very long signal paths, too many vias, and all of that leads to a lot of noise.

Solution:
- DO NOT change any placements for user interfaces; this incudes buttons, potentiometers, LEDS, switches, jacks for inputs and outputs
- DO move all parts that are related, to place them near each other.  

The goal is to minimize length of traces, and number of vias.

**Comment by nkakarla1** [comment]
In MEMS board, there were many opportunities for optimization. However, in piezo board, slight changes were made since the long traces were mainly due to placement of user interfaces.
