### ISSUE TITLE
Increase size of 2.7 uH inductor to previous version

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#38]
Increase the size of the 2.7 uH inductor to CR54 which is the same as it was in version V3-5 of the piezo preamp board.

**Comment by nkakarla1** [comment]
size of inductor changed to CR54

**Comment by Preetisar** [comment]
I do not see any change in L2 in the latest commit.

**Comment by nkakarla1** [comment]
I do not see any L2 in MEMS board. L1 was the 2.7uH inductor, which is changed to CR54.

**Comment by Preetisar** [comment]
Well technically it applied to both the boards. I should have put the labels for both.

**Comment by nkakarla1** [comment]
2.7uH Inductor changed to CR54 in both the boards.
