### ISSUE TITLE
Change power circuitry part of mixer board to same as piezo

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#39]
Name of file:
Mixer-Analog-OPA4134-Rev-K-multi under folder Mixer-Analog.

**Comment by nkakarla1** [comment]
Voltage regulation part changed to same as piezo.

**Comment by Preetisar** [comment]
In what version? I do not see any change in Rev L and but in Rev K. Shouldn't L come after K? Also the charging part is part of the voltage regulation (I know it is not obvious). So we need to change the charging circuit too.

**Comment by nkakarla1** [comment]
Naively, yes, L must be after K and I too checked that board first.However, it has same inconsistency problem between schematic and board. Due to that, and also since it was mentioned as revision K here, I made changes to the K revision.

**Comment by nkakarla1** [comment]
Yes, by voltage regulation I assumed it is the circuit which converts from one voltage level to another. Will update the charging part too and upload it.

**Comment by nkakarla1** [comment]
Power circuitry updated in version M.
