### ISSUE TITLE
Please remove the label 10BQ015  from the diode in the step up circuit

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#41]

**Comment by Preetisar** [comment]
Replace it with the following label: B130-13-F

**Comment by nkakarla1** [comment]
Diode label changed.

**Comment by Preetisar** [comment]
Diode label was not changed in the MEMS board, but only in the piezo board.

**Comment by nkakarla1** [comment]
It is changed in version V09. Anyways, to be on safer side, I have uploaded it again.
