### ISSUE TITLE
Trace from diode D2 to V+ is incorrectly labeled as VUSB.

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#42]
Please remove the incorrect label.

**Comment by nkakarla1** [comment]
trace renamed as V+

**Comment by Preetisar** [comment]
No name is required for that trace. Just remove the V+ too. Make it the same as the MEMS board, no labels on the trace.

**Comment by nkakarla1** [comment]
I have not put any explicit label on the trace. Once I removed the label, it was renamed as V+ since it was connected to V+ source.

**Comment by Preetisar** [comment]
OK its just that I don't see the trace labeled as V+ in the piezo board, so I was wondering if we could do the same for the mems board.
