### ISSUE TITLE
Add a 100 uH inductor and 0.1uF capacitor similar to piezo and mems board

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#43]
After the 12V output from the LDO, add a 100 uH inductor and a 0.1uF capacitor before the 12 V signal enters the audio circuitry similar to the mems and piezo board.

**Comment by nkakarla1** [comment]
Inductor and capacitor added at the 12V input to op-amps.

**Comment by Preetisar** [comment]
The voltage divider (at R51) should be connected after the inductor and capacitor, ie at the pin 4 of the opamp, and not directly to the +12V input line.
