### ISSUE TITLE
diods in piezo-preamp-tickler_V3-single-supply-OPA1612

### ISSUE THREAD

**Issue by batchku** [cmuartfab/eagle#5]
in `piezo-preamp-tickler_V3-single-supply-OPA1612`:

what kind of diods should D1 and D2 be:
![image](https://user-images.githubusercontent.com/518356/33529082-76c1016c-d839-11e7-847c-0be3593c73bc.png)

Is this general purpose diode appropriate?
https://www.digikey.com/product-detail/en/micro-commercial-co/1N4148W-TP/1N4148WTPMSCT-ND/717311

or should it be this zener diode:
https://www.digikey.com/product-detail/en/diodes-incorporated/MMSZ5231B-7-F/MMSZ5231B-FDICT-ND/755506

**Comment by jakezimmer** [comment]
They should be zeners for protection. If you ever see diodes laid out in that fashion (back to back), this is almost always the case. If the voltage gets too positive or two negative, they will short for protection.
