### ISSUE TITLE
Circular outline around C16 in mems board not showing up on the PCB

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#52]
C16 in MEMS board does not have circular outline in the PCB board, although it shows up in eagle. It may be that the silkscreen info for the caps is in the wrong layer in eagle, so they are not getting printed.
They need to be in `top/bottom-name/values`.

**Comment by nkakarla1** [comment]
A new device added to CMU_artfab library: CPOL-EU and modified to have the outlines in tValues layer.
All the current caps referenced to this new device.
