### ISSUE TITLE
LEDs for breakout circuit

### ISSUE THREAD

**Issue by Preetisar** [cmuartfab/eagle#6]
How are the LEDs exactly supposed to function for the charging and the voltage regulation part? In the current boards, the behavior is not consistent amongst boards. Also, the charging LED does not seem to shut off even after charging the battery for several hours. Should we have tested longer? Till what voltage?

**Comment by jakezimmer** [comment]
for this, you should play with the resistors on the leds. this might not be the "correct" thing to do but its worked for me in the past
